#!/bin/sh

VERSION="0.0.1"
input=$1

die() {
	err "$*"
	exit 1
}

err() {
	printf "\033[1;31m%s\033[0m\n" "$*" >&2
}

inf() {
	printf "\033[1;32m%s \033[1;35m%s\033[0m\n" "$1" "$2"
}

version_text() {
	inf "Version: $VERSION" >&2
}

help() {
    printf "%s\n" "Usage: $0 [ARGS]"
    printf "\n%s\n" "-h Show this menu and exits"
    printf "%s\n" "-U Fetch the update from GitHub"
    printf "%s\n" "-V Prints version number and exits"
    printf "%s\n" "-c Performs CPU benchmarks"
    printf "%s\n" "-a Performs API (CUDA) benchmarks"
    printf "%s\n" "-e Performs API (Vulkan) benchmarks"
}

[ -z $1 ] && help && exit 1


update_script() {
	#Get the newest version of the script
	update="$(curl -sL "https://raw.githubusercontent.com/DemonKingSwarn/demonbench/master/demonbench" | diff -u "$0" -)"
	if [ -z "$update" ]; then
		inf "Script is up to date :)"
	else
		if printf '%s\n' "$update" | patch "$0" - ; then
			inf "Script has been updated"
		else
			inf "Can't update for some reason!"
		fi
	fi
}

case $input in
    -h) help ;;
    -U) update_script ;;
    -V) version_text ;;
    -c) ./benchmarkers/geekbench_x86_64 --cpu ;;
    -a) ./benchmarkers/geekbench_x86_64 --compute CUDA ;;
    -e) ./benchmarkers/geekbench_x86_64 --compute Vulkan ;;
    *) printf "%s\n" "Invalid argument '$1'" && help && exit 1 ;;
esac
